# Understanding Data Types in Python

### A Python Integer is More Than Just an Integer

A single Integer, contains four pieces:

* ob_refcnt

* ob_type

* ob_size

* ob_digit

### A Python List Is More Than Just a List

In [3]:
L = list(range(10))

In [4]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
type(L[0])

int

In [6]:
L2 = [str(c) for c in L]

In [7]:
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [8]:
type(L2[0])

str

In [9]:
L3 = [True, '2', 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

Each item in python list is an object itself, what can make the process slower

Numpy Array is a fixed type, so it's much faster

### Fixed-Type Arrays in Python

In [12]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

'i' indicate the contents are integers

In [13]:
import numpy as np

### Creating Arrays from Python Lists

In [15]:
# iteger array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

if types not mach, Numpy will upcast if possible

In [17]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [18]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

NumPy arrays can be multi-dimensional

In [19]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Creating Arrays from Scratch

In [20]:
# Create a Length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [23]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.12100249, 0.34861711, 0.21996305],
       [0.55992973, 0.19138217, 0.85774172],
       [0.23838355, 0.844052  , 0.60627889]])

In [26]:
# Create a 3x3 array of normally distributed random values
# random values between 0 and 1
np.random.normal(0, 1, (3, 3))

array([[ 0.79211999,  1.11669518,  0.82674649],
       [ 0.92531398, -0.14176192,  1.76210351],
       [-0.05545472,  1.42119012, -0.94955284]])

In [28]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[2, 2, 2],
       [9, 5, 5],
       [4, 3, 0]])

In [29]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
# Create and uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

### NumPy Standard Data Types

Data type	Description

bool_	Boolean (True or False) stored as a byte

int_	Default integer type (same as C long; normally either int64 or int32)

intc	Identical to C int (normally int32 or int64)

intp	Integer used for indexing (same as C ssize_t; normally either int32 or int64)

int8	Byte (-128 to 127)

int16	Integer (-32768 to 32767)

int32	Integer (-2147483648 to 2147483647)

int64	Integer (-9223372036854775808 to 9223372036854775807)

uint8	Unsigned integer (0 to 255)

uint16	Unsigned integer (0 to 65535)

uint32	Unsigned integer (0 to 4294967295)

uint64	Unsigned integer (0 to 18446744073709551615)

float_	Shorthand for float64.

float16	Half precision float: sign bit, 5 bits exponent, 10 bits mantissa

float32	Single precision float: sign bit, 8 bits exponent, 23 bits mantissa

float64	Double precision float: sign bit, 11 bits exponent, 52 bits mantissa

complex_	Shorthand for complex128.

complex64	Complex number, represented by two 32-bit floats

complex128	Complex number, represented by two 64-bit floats